version: '3.12.3'

services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"  # Открываем порт базы данных для соединений

  # Сервис для Python-приложения
  backend:
    build: app
    container_name: python_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db  # Ожидаем, что база данных будет готова
    networks:
      - backend
    ports:
      - "8000:8000"  # Порт, на котором будет работать приложение
    volumes:
      - ~/my_docker/svg_data:/root/svg_data

  # frontend:
  #   build: front
  #   container_name: taro_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - NODE_ENV=development



# Объем для данных базы данных
volumes:
  pgdata:

# Сети для изоляции
networks:
  backend:
    driver: bridge